stages:
  - test

compliance:
  image: python:3.12
  stage: test
  script:
    - pip install ruff mypy vulture bandit pylint flake8 semgrep pyupgrade pytest pytest-cov pip-audit
    - ruff check . || true
    - mypy . || true
    - vulture . || true
    - bandit -r . || true
    - pylint main.py || true
    - flake8 . || true
    - semgrep --config auto . || true
    - pytest || true
